# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03c41383fd26ef2583f125949272ed5b81f68f5fec6f3ae56a7123374aa4d0aec816c6e5b804f20cbf5b2761abb05f133db2d323e93495b2c2814920e7f35dba

test:
  secret_key_base: e202fd23bbeda47a49a6831ebf82b8f4783edd9b23e6cafe68434dd574bf46a587bbd5c95e5f579969e9394f17511c0a70569923c856f0b407943f1f25790795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
